add model Products
2yar/InShop pull request #5
Opened 2017-01-27 10:53 UTC by gidpoiiohika

2017-01-27 14:41 UTC, yason4ik commented on app/controllers/products_controller.rb
> +    def index
лишние пробелы (настрой tab = 2 пробела)

2017-01-27 14:42 UTC, yason4ik commented on app/controllers/products_controller.rb
> +	def new
def end на одном уровне

2017-01-27 14:42 UTC, yason4ik commented on app/controllers/products_controller.rb
> +	def new
тоже пробелы

2017-01-27 14:43 UTC, gidpoiiohika commented on app/controllers/products_controller.rb
> +    def index
ок

2017-01-27 14:43 UTC, yason4ik commented on app/controllers/products_controller.rb
> +
зачем newline

2017-01-27 14:43 UTC, yason4ik commented on app/controllers/products_controller.rb
> +
newline

2017-01-27 14:46 UTC, yason4ik commented on app/controllers/products_controller.rb
> +
newline

2017-01-27 14:47 UTC, yason4ik commented on app/controllers/products_controller.rb
> +
лишня newline

2017-01-27 17:40 UTC, yason4ik commented on app/controllers/products_controller.rb
> +      @products = Product.find(params[:id])
екшен destroy выровнять

2017-01-27 17:41 UTC, yason4ik commented on app/controllers/products_controller.rb
>          params.require(:product).permit(:price, :name, :description, :image)
4 пробела

2017-01-27 17:41 UTC, yason4ik commented on app/controllers/products_controller.rb
> +end
добавить newline вконце

2017-01-27 17:42 UTC, yason4ik commented on app/models/product.rb
>  	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
2 пробела

2017-01-27 17:43 UTC, yason4ik commented on db/migrate/20170127110644_add_attachment_image_to_products.rb
> +	def change
def end на одном уровне

2017-01-27 17:47 UTC, yason4ik commented on app/views/products/index.html.erb
> +<%= link_to 'New product', new_product_path %>
добавить newline

2017-01-27 17:49 UTC, yason4ik commented on app/views/products/show.html.erb
> +<%= link_to("Back to list", products_path, class: 'back-link')%>
добавить newline и розобраться з пробеламы

2017-01-27 17:52 UTC, yason4ik commented on config/routes.rb
> +	root :to => "products#index"
переделать root to

2017-01-30 18:54 UTC, ezhenezhen commented on app/assets/stylesheets/products.scss
> + .products {
звідки цей цсс?
ти його сам писав?
за що він відповідає?
якщо він дійсно потрібен, то треба зробить нормальну ідентацію (отступи, пробели ітд)

2017-01-30 18:54 UTC, ezhenezhen commented on app/assets/stylesheets/products.scss
> +}
настрой саблайм щоб добавляв нову строку в кінці файла при збереженні

2017-01-30 18:54 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +    @products = Product.new
@product а не @products так як це однина. ти ж 1 продукт створюєш

2017-01-30 18:54 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +    @products = Product.create( product_params )
те саме, у тебе множина - треба однину. пробели в дужках лишні

2017-01-30 18:54 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +        format.json { render action: 'show', status: :created, location: @product }
думаю джейсон формат поки лишній

2017-01-30 18:54 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +        format.json { render json: @product.errors, status: :unprocessable_entity }
тут помилка, так як @product змінної у тебе не існує

2017-01-30 18:54 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +    @products = Product.find(params[:id])
@product

2017-01-30 18:54 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +    @products = Product.find(params[:id])
@product

2017-01-30 18:54 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +    redirect_to @products
на 2 пробела вправо

2017-01-30 18:54 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +    @products = Product.find(params[:id])
@product

2017-01-30 18:54 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +    @products = Product.find(params[:id])
@product

2017-01-30 18:54 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +    end
для чого тут ця перевірка? продукта може не бути в базі данних? тоді на чому визивається видалення його?

2017-01-30 18:54 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +      redirect_to root_url
на два пробела влево

2017-01-30 18:54 UTC, ezhenezhen commented on app/models/product.rb
> +	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
оступ 2 пробела, якшо в строке немає інтерполяції використовуєм одинарні кавички

2017-01-30 18:54 UTC, ezhenezhen commented on app/models/product.rb
> +	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
чим мотивувались саме такі розміри картинок?

2017-01-30 18:54 UTC, ezhenezhen commented on app/models/product.rb
> +	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
старий стиль хешей. використовуй новий

2017-01-30 18:54 UTC, ezhenezhen commented on app/views/layouts/application.html.erb
> +  <body class='<%= controller.controller_name %>'>
для чого тут цей клас?

2017-01-30 18:54 UTC, ezhenezhen commented on app/views/products/edit.html.erb
> +<div class="products edit">
у файлі повністю треба переробить індентацію (отступи)
ми використовуєм 2 пробела

2017-01-30 18:54 UTC, ezhenezhen commented on app/views/products/index.html.erb
> +
погана індентація, переробить треба повністю

2017-01-30 18:54 UTC, ezhenezhen commented on app/views/products/new.html.erb
> +
переробить індентацію

2017-01-30 18:54 UTC, ezhenezhen commented on app/views/products/show.html.erb
> +	<h2> Your details </h2>
переробить індентацію

2017-01-30 18:54 UTC, ezhenezhen commented on config/routes.rb
>  Rails.application.routes.draw do
отступ 2 пробела

2017-01-30 18:54 UTC, ezhenezhen commented on config/routes.rb
> +	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
лишній коммент

2017-01-30 18:54 UTC, ezhenezhen commented on db/migrate/20170127103503_create_products.rb
> +      t.float :price
default: 0

2017-01-30 18:54 UTC, ezhenezhen commented on db/migrate/20170127103503_create_products.rb
> +      t.float :weight
default: 0?

2017-01-30 18:54 UTC, ezhenezhen commented on db/migrate/20170127110644_add_attachment_image_to_products.rb
> +		add_attachment  :products, :image
отступи

2017-01-30 18:54 UTC, ezhenezhen commented on db/schema.rb
> +		t.float    "price"
а тут як умудрився отступи зробить неправильні?

2017-01-31 11:35 UTC, gidpoiiohika commented on app/assets/stylesheets/products.scss
> + .products {
цей ксс с кныжкы Гибкая разработка

2017-01-31 11:46 UTC, gidpoiiohika commented on app/assets/stylesheets/products.scss
> +}
ок

2017-01-31 11:51 UTC, yason4ik commented on app/assets/stylesheets/products.scss
> + .products {
ну я думаю мы будем использовать бутстрап или шось подобне.
так шо думаю пока вин не нада

2017-01-31 12:14 UTC, gidpoiiohika commented on app/controllers/products_controller.rb
> +    @products = Product.new
исправыв

2017-01-31 12:14 UTC, gidpoiiohika commented on app/controllers/products_controller.rb
> +    @products = Product.create( product_params )
справыв

2017-01-31 12:14 UTC, gidpoiiohika commented on app/controllers/products_controller.rb
> +        format.json { render action: 'show', status: :created, location: @product }
убрав

2017-01-31 13:23 UTC, gidpoiiohika commented on app/models/product.rb
> +	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
А да по поводу размеров? я просто зробыв як було в примери, яки размеры нада ?

2017-01-31 13:26 UTC, ezhenezhen commented on app/models/product.rb
> +	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
ну якшо ти не впевнений шо треба саме так може краще спитать у когось?
уяви шо тобі на роботі дали задачу, і не розказали всіх подробиць - просто спитав у того хто дав задачу і все.... ну або сам подумав і зробив...
ну а відповідь зробив так бо так було у прикладі - не гарна відповідь

2017-01-31 14:30 UTC, yason4ik commented on app/views/products/edit.html.erb
> +          <th>name</th>
2 лишних пробела

2017-01-31 14:30 UTC, yason4ik commented on app/views/products/index.html.erb
> +
ничого не выправлено

2017-01-31 14:30 UTC, yason4ik commented on app/views/products/new.html.erb
> +
ничого не выправлено

2017-01-31 14:31 UTC, yason4ik commented on app/views/products/show.html.erb
> +	<h2> Your details </h2>
ничого не выправлено

2017-01-31 14:32 UTC, yason4ik commented on config/routes.rb
>  Rails.application.routes.draw do
не выправлено

2017-01-31 14:33 UTC, yason4ik commented on db/migrate/20170127110644_add_attachment_image_to_products.rb
> +		add_attachment  :products, :image
ничого не выправлено

2017-01-31 14:34 UTC, yason4ik commented on db/schema.rb
> +		t.integer  "user_id"
зараз таб, треба 2 пробела

2017-01-31 14:47 UTC, gidpoiiohika commented on db/schema.rb
> +		t.integer  "user_id"
t.integer тут?  "user_id"

2017-01-31 14:48 UTC, ezhenezhen commented on db/schema.rb
> +		t.integer  "user_id"
вначале строки

2017-01-31 14:50 UTC, gidpoiiohika commented on db/schema.rb
> +		t.integer  "user_id"
так у мене там два пробела

2017-01-31 18:34 UTC, ezhenezhen requested changes
практично все вже ок.
треба трохи доробить

2017-01-31 18:34 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +
лишній newline

2017-01-31 18:34 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +    @product = Product.create( product_params )
в дужках не треба пробелов

2017-01-31 18:34 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> +  private
а от тут треба newline

2017-01-31 18:34 UTC, ezhenezhen commented on db/schema.rb
> +  create_table "carts", force: :cascade do |t|
звідки у цьому пулл реквесті взялася таблиця carts?
тут ти створюєш тільки products. в наступному буде carts

2017-01-31 18:34 UTC, ezhenezhen commented
плюс треба пофіксить конфлікти

2017-01-31 18:46 UTC, gidpoiiohika commented on db/schema.rb
> +  create_table "carts", force: :cascade do |t|
як все було. Я начав " хотив попробувать сробыты корзыну " 1. зайшов в ветку мастер создава нову ветку add_rart переключывся на цю ветку и на чав робыть, тоди побачыв шо в мене кучу помылок в products перейшов на ветку products и начав изминять. Мени тепер просто удалть

2017-01-31 18:46 UTC, gidpoiiohika commented on db/schema.rb
> +  create_table "carts", force: :cascade do |t|
create_table "carts", force: :cascade do |t|
    t.integer  "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

2017-02-13 10:40 UTC, ezhenezhen requested changes

2017-02-13 10:40 UTC, ezhenezhen commented on Gemfile.lock
> +<<<<<<< HEAD
конфлікт не порешав

2017-02-13 10:40 UTC, ezhenezhen commented on Gemfile.lock
> +=======
конфлікт

2017-02-13 10:40 UTC, ezhenezhen commented on app/controllers/products_controller.rb
> + def destroy
на 1 пробел правей

2017-02-13 10:40 UTC, ezhenezhen commented on config/routes.rb
> -  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
чого ти удалив ці строки?

2017-02-15 20:06 UTC, merged